### ISSUE TITLE
Некоторые замечания и рекомендации

### ISSUE THREAD

**Issue by RomanDanilov96** [lilproskater/hdrezka-client-releases#2]
В первую очередь хочу поблагодарить вас за отличное приложение. Если можно, я хотел бы высказать несколько замечаний/рекомендаций.

Во-первых, сама иконка приложения сейчас выглядит очень пикселизированно и нечетко (см. скришот ниже), и вообще, обрезка иконки сверху и снизу выглядит совсем не очень в визуальном плане. Даже сама HDrezka использует другую, красную иконку для своих продуктов. Только на сайте осталась эта обрезанная иконка. Как оптимальный вариант, можно взять иконку в стиле классической версии HDRezka Client для телефона, тогда просто иконка будет такая же, но уже не обрезанная сверху и снизу, или из самого приложения HDrezka App, которое теперь поддерживается самой HDrezka. При этом анимацию при открывании приложения можно спокойно оставлять. Уже готовые иконки я прикрепил ниже.

Во-вторых, заголовок окна в стиле macOS в Windows выглядит очень плохо. В идее, лучше использовать системную рамку окна, тем более в Windows 11 разворачивание поддерживает несколько вариантов расположение окон. Ну или оставлять программную рамку окна, но для версии под Windows хотя бы сделать подходящий классический стиль заголовка окна. Также, если будет использоваться программная рамка окна, желательно добавить всплывающие подсказки закрыть/свернуть/развернуть.

В-Третьих, на данный момент программа не поддерживает и не запоминает установленный размер окна, а также положение развернутой на полный экран. Сейчас, по умолчанию, окно выглядит уж слишком мелким и каждый раз растягивать его не самая приятная с задач.

В-Четвёртых, это уже запрос на функцию, очень не хватает функции открытия в стороннем плеере.

И еще несколько мелких замечаний. В зеркалах почему-то отсутствует hdrezka.ag и на нем не работает поиск, также в заголовке окна надпись HDRezka-Client – v2.0.0 выглядит слишком монструозно, по моему мнению гораздо лучше и чище выглядит просто надпись HDRezka Client, ну или HDrezka App, заметьте, что надписи отличаются, HD**R**ezka и HD**r**ezka, почему-то они теперь пишут r с малой буквы. Также, если использовать новую иконку HDrezka, то желательно также переименовать само приложение с Client на App, ваше приложение стилистическое гораздо больше напоминает App, чем спартанский Client 😉. И еще одно, на видео, которые не доступны в регионе, почему-то нет соответствующей надписи, наверняка блокировщик рекламы его тоже убирает. Это не очень хорошо, потому что видео нельзя воспроизвести, но непонятно почему, так как надписи о его недоступности в регионе тоже нет. Вроде все. Еще раз спасибо.

![1](https://github.com/lilproskater/hdrezka-client-releases/assets/139626195/a1d04013-99f9-417e-8294-4aeefe0e5c30)

[HDRezka.zip](https://github.com/lilproskater/hdrezka-client-releases/files/12061266/HDRezka.zip)

**Comment by RomanDanilov96** [comment]
В настройках увидел, что можно выбрать пункт открывать на полный экран при запуске приложения, извиняюсь. Но все равно, желательно было бы иметь возможность, возможно, даже в параметрах вынести отдельным пунктом, запомнить размер окна. Тогда программа запускалась сначала маленькая, для входной анимации, а потом уже переходила в заданный размер.

**Comment by RomanDanilov96** [comment]
В настройках увидел, что можно выбрать пункт открывать на полный экран при запуске приложения, извиняюсь. Но все равно, желательно было бы иметь возможность, возможно, даже в параметрах вынести отдельным пунктом, запомнить размер окна. Тогда бы программа запускалась сначала маленькая, для входной анимации, а потом уже переходила в заданный размер.

**Comment by RomanDanilov96** [comment]
Также к улучшениям, стоило бы добавить с левой стороны, где появляется кнопка вернуться на предыдущую страницу, еще кнопочку обновить страницу. Я знаю, что работает шорткат Ctrl+R, но иметь возможность обновить страницу с помощью мыши было бы просто замечательно.

**Comment by RomanDanilov96** [comment]
Еще заметил, что кнопка Об авторе, то есть о вас 😄 расположена только на главной странице, но при многих переходах по страницам, кнопка назад становится также доступа на главной странице и это нормально, но тогда кнопка Об авторе несколько мешает и выглядит странно. Я бы попросил, чтобы вы, пожалуйста, переместили ее все же справа с любой из сторон возле кнопки настроек. Так будет удобнее, ее можно будет вызвать с любого места, тем более, она также служит информационной панелью шорткатов, и там она не будет забирать такого фокуса на себя, чем когда она расположена одна слева и пересекается с кнопкой назад, тем более, как я отмечал выше, там желательно все же расположить дополнительную кнопку для перезагрузки страницы.

![1](https://github.com/lilproskater/hdrezka-client-releases/assets/139626195/21dfea0a-2abf-476a-a0ef-b1d519ae3949)

**Comment by RomanDanilov96** [comment]
И еще, при открытии любого фильма или сериала он автоматически попадает в историю, что не очень практично в плане дальнейшего использования, так как она этим сильно засоряется и становится не очень информативной. Было б здорово, если бы вы, несмотря на "Историю", добили также функцию "Досмотреть", по анологии с HDrezka, куда попадают только видео при воспроизведении, то есть, только после начала просмотра. Это довольно удобная функция, и по-моему, более чаще используемая.

**Comment by RomanDanilov96** [comment]
И такой, маленький нюанс, я бы сказал, даже спорный, фиолетовый цвет для ползунков в плеере выглядит несколько странным и непривычным. Более классический светло-синий вариант будет выглядеть более предпочтительным.

**Comment by RomanDanilov96** [comment]
И самое главное, насколько я понимаю API HDrezka это позволяет, было бы очень здорово, если бы вы смогли добавить функцию входа в аккаунт для синхронизации закладок и т.д. В HDrezka App функция входа появилась еще до того, как посторонние разработчики передали ее команде HDrezka, поэтому, я предполагаю, что это технически возможно реализовать с поддержкой синхронизации.

**Comment by lilproskater** [comment]
Спасибо большое за отзыв и рекомендации Роман. Буду постепенно добавлять понравившиеся идеи в следующие версии)
