### ISSUE TITLE
Не работает поиск

### ISSUE THREAD

**Issue by barl0g** [lilproskater/hdrezka-client-releases#3]
Набираю, например,  "мастер" - пишет "ничего не найдено, возможно это связано с вашим зеркалом."

Фильмы показывает.

**Comment by lilproskater** [comment]
Здравствуйте, с поиском бывают проблемы со стороны серверов HDRezka, Поиск у многих работает корректно, только вот у некоторых пользователей наблюдаются проблемы. Данный баг является фантомным и его сложно отследить и воспроизвести чтобы исправить данную проблему, так как возможно это связано с регионами и сетью. Спасибо за feedback, постараемся исправить в ближайшем будущем!
