### ISSUE TITLE
Подменю Фильмы -> "вестерны, биографические" и т.д. не работает

### ISSUE THREAD

**Issue by barl0g** [lilproskater/hdrezka-client-releases#5]
В сериалах и мультфильмах и аниме тоже.

**Comment by lilproskater** [comment]
Проблема без продробного описания. Сейчас проверил у себя, все работает корректно. Возможно на время создания данного issue была проблема со стороны сервера. Прошу в следующий раз описать проблему подробнее и указать точные шаги для воспроизведения проблемы. Благодарю
